### ISSUE TITLE
Logo and favicon

### ISSUE THREAD

**Issue by Alfenstein8** [Alfenstein8/Vektorskak-online#9]
A logo and favicon for the game.

**Comment by Koda-Pig** [comment]
Hi @Alfenstein8, I made a simple logo/ favicon and added it. My pull request here: https://github.com/Alfenstein8/Vektorskak-online/pull/13

**Comment by Alfenstein8** [comment]
@Koda-Pig yay, thank you! It reminds me a bit of the MasterCard logo, but I dig it :)

**Comment by Koda-Pig** [comment]
Glad you like it :)
